---
apiVersion: v1
kind: Service
metadata:
  name: mv-user-service
spec:
  selector:
    app: mv-user
  ports:
  - protocol: 'TCP'
    port: 3333
    targetPort: 3333
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mv-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mv-user
  template:
    metadata:
      labels:
        app: mv-user
    spec:
      containers:
      - name: mv-user
        image: registry.digitalocean.com/mv-user/mv_user_server:4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3333
