---
apiVersion: v1
kind: Service
metadata:
  name: mv-user-service
spec:
  selector:
    app: mv-user
  ports:
  - protocol: 'TCP'
    port: 3333
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mv-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mv-user
  template:
    metadata:
      labels:
        app: mv-user
    spec:
      containers:
      - name: mv-user
        image: registry.digitalocean.com/mv-user/mv_user_server:0.0.8
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mv-user-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    name: mv-user-ingress
spec:
  rules:
  - host: mv-user.api-mv.com.br
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mv-user-service
            port:
              number: 80
